export { default as DashboardLayout } from './dashboardLayout/DashboardLayout'
// export { default as SalePerMontPrice } from './resumen/SalePerMontPrice'
// export { default as SalePerMontProduct } from './resumen/SalePerMontProduct'
// export { default as ProductMoreSold } from './resumen/ProductMoreSold'
// export { default as BalancePerMont } from './resumen/BalancePerMont'
// export { default as BalanceCurrentMont } from './resumen/BalanceCurrentMont'
// export { default as RegisterUser } from './resumen/RegisterUser'
// export { default as TableUser } from './tables/users'
// export { default as TableTransaction } from './tables/transaction'
// export { default as TableApply } from './tables/apply'
// export { default as TableMyTransaction } from '../dashboard/dashboardUser/myTransaction'
export { default as UserUpdate } from './dashboardUser/UpdateUser'
export { default as Profile } from './dashboardUser/Profile'