import Head from 'next/head';
import {InferGetServerSidePropsType} from 'next';
import {NextPage} from 'next/types';
import { 
  getServe
 } from '../utils/fetchingDB';

const Home = ({data}:InferGetServerSidePropsType<typeof getServe>)=>{

  console.log(data)
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          Hola mundo!!!
        </h1>
      </main>
    </>
  );
};

export default Home;
